-- Logos: `insights` table. Run in Supabase → SQL Editor.

create table if not exists public.insights (
  id              bigint generated by default as identity primary key,
  category        text   not null
                  check (category in ('Health','Science','Enlightenment','Philosophy','Technology')),
  title           text   not null,
  card_body       text[] not null default '{}',
  actionable_step text   not null,
  source_name     text   not null,
  affiliate_url   text,
  created_at      timestamptz not null default now()
);

-- Public, read-only access for the anon key. Writes go through the dashboard only.
alter table public.insights enable row level security;

drop policy if exists "Public read access" on public.insights;
create policy "Public read access"
  on public.insights for select
  to anon, authenticated
  using (true);

-- Seed rows (same as src/data/seedInsights.js).
insert into public.insights (category, title, card_body, actionable_step, source_name, affiliate_url) values
('Philosophy', 'The Cosmopolitan Duty',
  array['Ancient Stoics rejected isolation and hyper-individualism.',
        'They viewed humanity as a single interconnected organism (Sympatheia).',
        'True virtue requires active, ethical participation in your local community.'],
  'Choose one small action today that serves someone else without expecting praise.',
  'Meditations by Marcus Aurelius', 'https://amazon.com'),
('Health', 'Circadian Anchoring',
  array['Viewing natural sunlight within 30-60 minutes of waking triggers a critical cortisol peak.',
        'This biological timer sets a countdown clock for nighttime melatonin production.',
        'Looking through a window or screen does not work; photic energy must hit retinal cells directly.'],
  'Step outside for 10 minutes immediately after waking up, even if it is overcast.',
  'Stanford University Medicine (Huberman Lab)', 'https://amazon.com'),
('Science', 'Goodhart’s Law',
  array['''When a measure becomes a target, it ceases to be a good measure.''',
        'Optimizing strictly for arbitrary metrics causes people to subconsciously game the system.',
        'This destroys the actual, underlying quality or health goal you originally aimed for.'],
  'Identify one metric you are obsessing over and switch focus entirely to the systemic habit.',
  'Charles Goodhart Economics Studies', 'https://amazon.com'),
('Enlightenment', 'The Second Arrow Principle',
  array['Buddhist psychology states that life shoots two distinct arrows at us.',
        'The first arrow is the unavoidable external event (pain, bad luck, a rude comment).',
        'The second arrow is your emotional reaction to it. The second arrow is entirely self-inflicted.'],
  'When something minor goes wrong today, tell yourself: ''The first arrow landed. I will not shoot myself with the second.''',
  'The Sallatha Sutta (Ancient Text)', 'https://amazon.com'),
('Technology', 'Amdahl’s Law for Productivity',
  array['Optimizing a tech component that only handles 5% of a task yields almost zero macro speedup.',
        'Similarly, spending hours tweaking your app''s font or layout is a waste of mental energy.',
        'You must locate and systematically optimize the absolute bottleneck of your workflow.'],
  'Find the single task causing 80% of your daily delays, and focus your energy on fixing just that.',
  'Gene Amdahl (Computer Architecture)', 'https://amazon.com');
